/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-20 08:52:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 String idkey = (String)session.getAttribute("idkey"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>해피레고</title>\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Play:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css\"  media=\"screen\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/content.css\"  media=\"screen\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/base.css\" media=\"screen\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" media=\"screen\">\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/lego_32.ico\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- wrap -->\n");
      out.write("<section id=\"wrap\">\n");
      out.write("    \n");
      out.write("\t<!-- main_con -->\n");
      out.write("\t<section id=\"main_con\">\t\n");
      out.write("\t\t<!-- txt_wrap -->\n");
      out.write("\t\t<div class=\"txt_wrap\">\n");
      out.write("\t\t\t<h1><img src=\"images/lego.png\" alt=\"해피레고\" width=\"200\"/></h1>\n");
      out.write("\t\t\t<p><img src=\"images/main_sub_title.png\" width=\"350\" alt=\"레고와 동심 그리고 해피레고 해피레고에서 처음 만나는 기분 좋은 설레임!\"/></p>\n");
      out.write("\t\t\t<ul class=\"main_list\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<li class=\"list01\">\n");
      out.write("\t\t\t\t\t<div class=\"d_t\">\n");
      out.write("\t\t\t\t\t\t<div class=\"d_c\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"service/product/product.jsp\">서비스신청</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li class=\"list02\">\n");
      out.write("\t\t\t\t\t<div class=\"d_t\">\n");
      out.write("\t\t\t\t\t\t<div class=\"d_c\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"company/happy/companyindex.jsp\">회사소개</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li class=\"list03\">\n");
      out.write("\t\t\t\t\t<div class=\"d_t\">\n");
      out.write("\t\t\t\t\t\t<div class=\"d_c\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"guide/guidelist/guideindex.jsp\">이용안내</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li class=\"list04\">\n");
      out.write("\t\t\t\t\t<div class=\"d_t\">\n");
      out.write("\t\t\t\t\t\t<div class=\"d_c\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"community/qna/qnaList.jsp\">Q&amp;A</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li class=\"list05\">\n");
      out.write("\t\t\t\t\t<div class=\"d_t\">\n");
      out.write("\t\t\t\t\t\t<div class=\"d_c\">\n");
      out.write("\t\t\t\t\t\t\t");
if(idkey == null){
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mypage/member/login.jsp\">마이페이지</a>\n");
      out.write("               \t\t\t\t");
}else if(idkey.equals("manager")){
      out.write("\n");
      out.write("             \t\t       \t<a href=\"mypage/admin/manager.jsp\" title=\"마이페이지\">관리자</a>\n");
      out.write("\t\t\t\t\t\t\t");
}else{
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mypage/member/myinfo.jsp\" title=\"마이페이지\">마이페이지</a>\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- //txt_wrap -->\n");
      out.write("\n");
      out.write("\t\t<!-- av_wrap -->\n");
      out.write("\t\t<div class=\"av_wrap\">\t\t\t\n");
      out.write("\t\t\t<video autoplay loop muted poster=\"images/av_bg.jpg\" id=\"av\">\n");
      out.write("\t\t\t\t<source src=\"images/Swing.mp4\">\n");
      out.write("\t\t\t\t<source src=\"images/av_bg.webm\">\n");
      out.write("\t\t\t\t<img src=\"images/av_bg.jpg\"/>\n");
      out.write("\t\t\t</video>\n");
      out.write("\t\t\t<p class=\"dot\"></p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- //av_wrap -->\n");
      out.write("\n");
      out.write("\t</section>\n");
      out.write("\t<!-- //main_con -->\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t$(document).ready(function(){\t\t\n");
      out.write("\t\t//guideH();\n");
      out.write("\t\t$('#footer').css('margin-top',0);\n");
      out.write("\t\tresize();\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$(window).resize(function(){\t\t\n");
      out.write("\t\tresize();\n");
      out.write("\t});\n");
      out.write("\n");
      out.write(" var resize = function() {\n");
      out.write("\t//console.log('resize');\n");
      out.write("\tvar $node = $('.av_wrap');\n");
      out.write("\tvar ratio = 16/9;\n");
      out.write("\tvar width = $node.parent().width(),\n");
      out.write("\t\tpWidth, // player width, to be defined\n");
      out.write("\t\theight = $node.parent().height(),\n");
      out.write("\t\tpHeight, // player height, tbd\n");
      out.write("\t\t$av = $('#av');\n");
      out.write("\n");
      out.write("\t// when screen aspect ratio differs from video, video must center and underlay one dimension\n");
      out.write("\n");
      out.write("\tif (width / ratio < height) { // if new video height < window height (gap underneath)\n");
      out.write("\t\tpWidth = Math.ceil(height * ratio); // get new player width\n");
      out.write("\t\t$av.width(pWidth).height(height).css({left: (width - pWidth) / 2, top: 0}); // player width is greater, offset left; reset top\n");
      out.write("\t} else { // new video width < window width (gap to right)\n");
      out.write("\t\tpHeight = Math.ceil(width / ratio); // get new player height\n");
      out.write("\t\t$av.width(width).height(pHeight).css({left: 0, top: (height - pHeight) / 2}); // player height is greater, offset top; reset left\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <aside id=\"pop\" style=\"display:none;\">\n");
      out.write("        <!-- pop_table -->\n");
      out.write("        <section class=\"pop_table\">\n");
      out.write("            <!-- pop_cell -->\n");
      out.write("            <div class=\"pop_cell\" id=\"popdetail\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("    </aside>\n");
      out.write("    <div id=\"commonLayer\">\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- //wrap -->\n");
      out.write("\n");
      out.write("<!-- //wrap -->\n");
      out.write("<aside id=\"lnb\">\n");
      out.write("    <p class=\"lnb_bg\" ></p>\n");
      out.write("   <!-- lnb_wrap -->\n");
      out.write("    <div class=\"lnb_wrap\">\n");
      out.write("        <!-- lnb_group -->\n");
      out.write("        <div class=\"lnb_group\">\n");
      out.write("            <!-- lnb_top -->\n");
      out.write("            <div class=\"lnb_top\">\n");
      out.write("\n");
      out.write("                <p class=\"top03\"><a href=\"/member/nonmember.jsp\" title=\"예약확인\"><span>서비스신청</span></a></p>\n");
      out.write("            </div>\n");
      out.write("            <!-- //lnb_top -->\n");
      out.write("            <!--\n");
      out.write("            //\tli 태그에 actived 클래스 추가시 활성화\n");
      out.write("            -->\n");
      out.write("            <ul>\n");
      out.write("                <li >\n");
      out.write("                    <p class=\"one_depth\" ><a href=\"/reservation/index.jsp\" class=\"btn_one\" title=\"실시간예약\">서비스신청</a></p>\n");
      out.write("                </li>\n");
      out.write("                <li >\n");
      out.write("                    <p class=\"one_depth\" ><a href=\"/service/\" class=\"btn_one\" title=\"해피렌트카\">해피렌트카</a></p>\t\t\t\t\t\t\n");
      out.write("                </li>\n");
      out.write("                <li >\n");
      out.write("                    <p class=\"one_depth\" ><a href=\"/premium/\" class=\"btn_one\" title=\"편의장비\">편의장비</a></p>\t\t\t\t\t\t\n");
      out.write("                </li>\n");
      out.write("                <li >\n");
      out.write("                    <p class=\"one_depth\" ><a href=\"/guide/guideList.jsp\" class=\"btn_one\" title=\"대여가이드\">대여가이드</a></p>\n");
      out.write("                </li>\n");
      out.write("                <li >\n");
      out.write("                    <p class=\"one_depth\" ><a href=\"#\" class=\"btn_one kor\" title=\"커뮤니티\">커뮤니티</a></p>\n");
      out.write("                    <ul class=\"snb\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/community/qna/qnaList.jsp\" title=\"QnA\">Q&amp;A</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/community/faq/faqList.jsp\" title=\"자주묻는질문\">자주묻는질문</a></li>\n");
      out.write("                        <li><a href=\"/community/notice/noticeList.jsp\" title=\"공지사항\">공지사항</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("                <li >\n");
      out.write("                    <p class=\"one_depth\" ><a href=\"/events/eventList.jsp\" class=\"btn_one\" title=\"이벤트\">마이페이지</a></p>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <!-- //lnb_group -->\n");
      out.write("    </div>\n");
      out.write("    <!-- //lnb_wrap -->\n");
      out.write("</aside>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- footer -->\n");
      out.write("<footer id=\"footer\">\n");
      out.write("\t<section class=\"footer_wrap\">\n");
      out.write("\t\t<h2>\n");
      out.write("\t\t\t<img src=\"images/lego_128.png\" alt=\"해피레고\" width=\"5%\" />\n");
      out.write("\t\t</h2>\n");
      out.write("\t\t<address>\n");
      out.write("\t\t\t해피레고&nbsp;&nbsp;|&nbsp;&nbsp; 프로젝트\n");
      out.write("\t\t\t&nbsp;&nbsp;|&nbsp;&nbsp;팀: 장현진, 이연남, 이동규, 오현은\n");
      out.write("\t\t\t&nbsp;&nbsp;|&nbsp;&nbsp;주소지 : 서울특별시 강남 에이콘아카데미<br>\n");
      out.write("\t\t\t사업자등록번호 : 000-0000-0000&nbsp;&nbsp;|&nbsp;&nbsp;통신판매신고번호 : 제\n");
      out.write("\t\t\t0000-서울강남-0000호&nbsp;&nbsp;|&nbsp;&nbsp;<span class=\"letter\">TEL\n");
      out.write("\t\t\t: 1004-1004</span>&nbsp;&nbsp;|&nbsp;&nbsp;<span class=\"letter\">Fax\n");
      out.write("\t\t\t: 000-000-0000</span><br> <span class=\"letter\">COPYRIGHT©2016\n");
      out.write("\t\t\tHAPPY LEGO. ALL RIGHTS RESERVED.</span>\n");
      out.write("\t\t</address>\n");
      out.write("\t</section>\n");
      out.write("</footer>\n");
      out.write("<!-- //footer -->\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
